<?php
// Создаём заголовок страницы, который загрузится в layout
$title = $this->title;
$description = $this->title;
$texttop = "";
if ($this->seocategory != null) {
	$title = $this->seocategory->title;
	$description = $this->seocategory->description;
	$texttop = $this->seocategory->texttop;
}
$this->headTitle($title);

$keywords = "";
foreach ($this->rezume as $rezumeItem) {
    $filter = new Zend_Filter_Keywords(10);
	$keyword = $filter->filter($rezumeItem->about);
	$keywords = $keywords . $keyword;
}

//$this->headMeta()->setName('keywords', $keywords);	
$this->headMeta()->setName('description', $description);
?>

<table cellspacing="0"><tr>  
<!-- LEFT COLUMN start -->    
<!-- SUBMENU start -->
<td class="left">
<div class="left-width">
 <ul class="submenu">
	<li><a href='/rezume/addrezume'><span class='span_submenu'>Добавить резюме</a></span></li> 
	<?php echo $this->partialLoop('partials/categorylist_rezume.phtml', $this->indexcategory);?>
 </ul>
 <table cellspacing="0" class="featured">
   <tr>
     <td>
     <div class="border-block">
	 <div class="b">
	 <div class="l">
	 <div class="r">
	 <div class="l-t">
	 <div class="r-t">
	 <div class="l-b">
	 <div class="r-b">
	 
		<script type="text/javascript"><!--
		google_ad_client = "ca-pub-5051941505461758";
		/* vacancy_left */
		google_ad_slot = "4379081732";
		google_ad_width = 300;
		google_ad_height = 250;
		//-->
		</script>
		<script type="text/javascript"
		src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
		</script>

	 </div>
	 </div>
	 </div>
	 </div>
	 </div>
	 </div>
	 </div>
	 </div>
	 </td>
   </tr>
   <tr>
     <td>
     <div class="border-block">
	 <div class="b">
	 <div class="l">
	 <div class="r">
	 <div class="l-t">
	 <div class="r-t">
	 <div class="l-b">
	 <div class="r-b">
	 
	 <span class="textleft">
		<?php 
			$texttop = "";
			if ($this->seocategory != null) {
				$texttop = $this->seocategory->textleft;
			}
			echo $texttop; 
		?>
	 </span>

	 </div>
	 </div>
	 </div>
	 </div>
	 </div>
	 </div>
	 </div>
	 </div>
	 </td>
   </tr>   
 </table>
 </div>
 </td>  
 <!-- LEFT COLUMN end -->  
 <!-- MAIN COLUMN start -->
 <td class="center">
 
 <span class="h1-page-title">
 <a href='/'>Главная</a><span class='slash'>\\</span><span class='prod'></span>
 </span>
 
 <div class="main-content">
 <div class="latest-news">
   <div class="new-content">
	<span class="h2-latest-news">
		<?php 
			$texttop = "";
			if ($this->seocategory != null) {
				$texttop = $this->seocategory->texttop;
			}
			echo $texttop; 
		?>
	</span>
   </div>
   <div class="news-header">
   <div class="bg-left">
   <div class="bg-right">
   <div>
     <h1 class="h1-latest-news"><?php echo $this->title; ?></h1>
	 <span class= "addpost"><a href='/rezume/addrezume'>Добавить резюме</a></span>
   </div>
   </div>
   </div>
   </div>
   <?php
		echo $this->partialLoop('partials/rezumelist.phtml', $this->rezume);
		echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); 
   ?>
 
 </div>    
 <!-- MAIN CONTENT end -->
 </div>
 </td>  <!-- MAIN COLUMN end -->
 </tr>
 </table>





