<?php
// Создаём заголовок страницы, который загрузится в layout
$this->title = "Объявление";
$this->headTitle($this->rezume['current_rezume']->title);
$this->headMeta()->setName('description', $this->rezume['current_rezume']->about); 

$Keywords = new Zend_Filter_Keywords(10);
$this->headMeta()->setName('keywords', $Keywords->filter($this->rezume['current_rezume']->about));   
?>

<table cellspacing="0"><tr>  
<!-- LEFT COLUMN start -->    
<!-- SUBMENU start -->
<td class="left">
<div class="left-width">
 <ul class="submenu">
    <li><a href='/rezume/addrezume'><span class='span_submenu'>Добавить резюме</a></span></li> 
    <?php echo $this->partialLoop('partials/categorylist_rezume.phtml', $this->indexcategory['list']);?>
 </ul>
 <table cellspacing="0" class="featured">
   <tr>
     <td>
     <div class="border-block">
     <div class="b">
     <div class="l">
     <div class="r">
     <div class="l-t">
     <div class="r-t">
     <div class="l-b">
     <div class="r-b">
     
        <script type="text/javascript"><!--
        google_ad_client = "ca-pub-5051941505461758";
        /* vacancy_left */
        google_ad_slot = "4379081732";
        google_ad_width = 300;
        google_ad_height = 250;
        //-->
        </script>
        <script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
        </script>

     </div>
     </div>
     </div>
     </div>
     </div>
     </div>
     </div>
     </div>
     </td>
   </tr> 
 </table>
 </div>
 </td>  
 <!-- LEFT COLUMN end -->  
 <!-- MAIN COLUMN start -->
 <td class="center">
 
 <span class="h1-page-title">
<a href='/'>Главная</a><span class='slash'>\\</span><span class='prod'></span>
<a href="<?php echo $this->url(array('controller'=>'rezume', 'action'=>'listrezume', 'id'=>$this->rezume['current_rezume']->categoryid));?>"><?php echo $this->indexcategory['current_category']->category_name;?></a><span class='slash'>\\</span><span class='prod'></span>
</span>  

 <div class="main-content">
 <div class="latest-news">
   <div class="news-header">
   <div class="bg-left">
   <div class="bg-right">
   <div>
     <h1 class="h1-latest-news"><?php echo 'Резюме в Томске: '. $this->rezume['current_rezume']->title; ?></h1>
   </div>
   </div>
   </div>
   </div>

   <div>
    <h3>О себе:</h3>
    <?php echo $this->rezume['current_rezume']->about; ?> 
   </div>
   
   <div>
    <h3>Образование:</h3>
    <?php echo $this->rezume['current_rezume']->education; ?> 
   </div>
   
   <div>
    <h3>Навыки:</h3>
    <?php echo $this->rezume['current_rezume']->skills; ?> 
   </div>
   
   <div>
    <h3>Опыт работы:</h3>
    <?php echo $this->rezume['current_rezume']->experience; ?> 
   </div>
   
   <div>
    <h3>Прочее:</h3>
    <?php echo $this->rezume['current_rezume']->other; ?> 
   </div>
   
   <div>
    <h3>Контакты:</h3>
    <?php echo $this->rezume['current_rezume']->contacts; ?> 
   </div>
   
   <div>
   <h3> Дата публикации:  
   <?php 
       $date = new Zend_Date($this->rezume['current_rezume']->date); 
       $createdDate= $date->get(Zend_Date::DATE_LONG); 
       echo $createdDate;
   ?> 
   </h3> 
   </div>     
 </div>    
 <!-- MAIN CONTENT end -->
 </div>
 
 <div class="latest-news">
   <div class="news-header">
   <div class="bg-left">
   <div class="bg-right">
   <div>
    <!-- <h1 class="h1-latest-news"><?php //echo 'Похожие вакансии: '; ?></h1> -->
   </div>
   </div>
   </div>
   </div>

   <?php
     //echo $this->partialLoop('partials/rezumelist.phtml', $this->rezume['similar_rezume']);
   ?>
   
 </div>    
 <!-- MAIN CONTENT end -->
 </div>
 </td>  <!-- MAIN COLUMN end -->
 </tr>
 </table>




  


