<?php
// Создаём заголовок страницы, который загрузится в layout
$this->title = "Кадровые агентства Томска";
$this->headTitle($this->title);

$this->headMeta()->setName('keywords', 'агентства, томск, список, кадровые, адрес');        
$this->headMeta()->setName('description', 'Кадровые агенства в Томске. Список агенств, которые занимаются услугами в области занятости. Все агентства');
?>

<div class="span8">
<?php
	echo $this->partialLoop('partials/agency.phtml', $this->agency);
	echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); 
?>
</div> 

<div class="span4">
	<ul class="nav nav-tabs nav-stacked">
		<?php echo $this->partialLoop('partials/categorylist.phtml', $this->indexcategory);?>
	</ul>
</div> 


