<?php
    // Создаём заголовок страницы, который загрузится в layout
    $this->title = "Добавить объявление";
    $this->headTitle($this->title);
?>
<div class="span8">
	<div class="well">
	<?php
		echo $this->form;
	?>
	</div> 
 </div> 	
<div class="hidden-phone span4">
	<ul class="nav nav-tabs nav-stacked">
		<?php echo $this->partialLoop('partials/categorylist.phtml', $this->indexcategory);?>
	</ul>
</div>		
 
