<?php
// Создаём заголовок страницы, который загрузится в layout
$title = $this->title;
$description = $this->title;
$texttop = "";
if ($this->seocategory != null) {
    $title = $this->seocategory->title;
    $description = $this->seocategory->description;
    $texttop = $this->seocategory->texttop;
}
$this->headTitle($title);

$keywords = "";
foreach ($this->post as $postItem) {
    $filter = new Zend_Filter_Keywords(10);
    $keyword = $filter->filter($postItem->text);
    $keywords = $keywords . $keyword;
}

//$this->headMeta()->setName('keywords', $keywords);    
$this->headMeta()->setName('description', $description);
?>

<div class="span8">
<?php
	echo $this->partialLoop('partials/postlist.phtml', $this->post);
	echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); 
?>
</div> 

<div class="span4">
	<a href="<?php echo '/' . Zend_Registry::get('controller') . '/add' . $this->category_id ?>" class="btn btn-block btn-success">Добавить вакансию</a>
	<ul class="nav nav-tabs nav-stacked">
		<?php echo $this->partialLoop('partials/categorylist.phtml', $this->indexcategory);?>
	</ul>
</div> 



