<?php
// Создаём заголовок страницы, который загрузится в layout
$this->title = "Статьи";
$this->headTitle($this->title);

$keywords = "";
foreach ($this->blog as $blogItem) {
    $filter = new Zend_Filter_Keywords(10);
	$keyword = $filter->filter($blogItem->text);
	$keywords = $keywords . $keyword;
}

$this->headMeta()->setName('keywords', $keywords);		
$this->headMeta()->setName('description', $this->title);
?>

<div class="span8">
<?php
	echo $this->partialLoop('partials/bloglist.phtml', $this->blog);
	echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); 
?>
</div> 

<div class="span4">
	<ul class="nav nav-tabs nav-stacked">
		<?php echo $this->partialLoop('partials/categorylist.phtml', $this->indexcategory);?>
	</ul>
</div> 

