<?php
// Создаём заголовок страницы, который загрузится в layout
$this->title = "Объявление";
$this->headTitle('Требуется ' . $this->post['current_post']->title);
$this->headMeta()->setName('description', $this->post['current_post']->text); 

$Keywords = new Zend_Filter_Keywords(10);
$this->headMeta()->setName('keywords', $Keywords->filter($this->post['current_post']->text));   
?>
<div class="span8">
	<div class="well">	
	
		<h3><?php echo $this->post['current_post']->title; ?></h3>
		<h4>Дата публикации:  
			<?php 
				$date = new Zend_Date($this->post['current_post']->date); 
				$createdDate= $date->get(Zend_Date::DATE_LONG); 
				echo $createdDate;
			?> 
		</h4>
		
		<div class="media pull-left">
			<div class="pull-left">
				<script type="text/javascript"><!--
				google_ad_client = "ca-pub-5051941505461758";
				/* vacancy_left */
				google_ad_slot = "4379081732";
				google_ad_width = 300;
				google_ad_height = 250;
				//-->
				</script>
				<script type="text/javascript"
				src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</div>
		
		<p><?php echo $this->post['current_post']->text; ?> 
			<br> 
		</p>
		<p class="btn btn-warning"><?php echo 'Оклад: ' . $this->post['current_post']->price;?>
			<br> 
		</p>
	</div>

		<!-- Яндекс.Директ -->
		<script type="text/javascript">
		//<![CDATA[
		yandex_partner_id = 114758;
		yandex_site_bg_color = 'EEEEEF';
		yandex_site_charset = 'utf-8';
		yandex_ad_format = 'direct';
		yandex_font_size = 1;
		yandex_direct_type = 'horizontal';
		yandex_direct_limit = 2;
		yandex_direct_title_font_size = 3;
		yandex_direct_title_color = '0000CC';
		yandex_direct_url_color = '006600';
		yandex_direct_text_color = '000000';
		yandex_direct_hover_color = '0066FF';
		yandex_direct_favicon = false;
		document.write('<sc'+'ript type="text/javascript" src="http://an.yandex.ru/system/context.js"></sc'+'ript>');
		//]]>
		</script>

	<table class="table">
    <tbody>
	<?php
		echo $this->partialLoop('partials/postlist_link.phtml', $this->post['similar_post']);
	?>
    </tbody>
    </table>		
	
</div>
<div class="span4">
	<a href="<?php echo '/' . Zend_Registry::get('controller') . '/add' . $this->category_id ?>" class="btn btn-block btn-success">Добавить вакансию</a>
	<ul class="nav nav-tabs nav-stacked">
		<?php echo $this->partialLoop('partials/categorylist.phtml', $this->indexcategory['list']);?>
	</ul>
</div> 




  


