<?php
$this->headTitle($this->blog->title);

$Keywords = new Zend_Filter_Keywords(10);
$this->headMeta()->setName('keywords', $Keywords->filter($this->blog->text));

$Description = substr($this->blog->text, 0, 200);
$this->headMeta()->setName('description', $Description);
    
?>
<div class="span8">
	<div class="well">
		<h3><?php echo $this->blog->title; ?></h3>
		<h4></h4>
		<p><?php echo $this->blog->text; ?> 
			<br> 
		</p>
		<p>Дата публикации:  
			<?php 
				$date = new Zend_Date($this->blog->date); 
				$createdDate= $date->get(Zend_Date::DATE_LONG); 
				echo $createdDate;
			?> 
			<br> 
		</p>
	</div>
</div>
<div class="span4">
	<ul class="nav hidden-phone nav-list">
		<?php echo $this->partialLoop('partials/categorylist.phtml', $this->indexcategory);?>
	</ul>
</div>   