<?php
// Создаём заголовок страницы, который загрузится в layout
$this->title = "Мои объявления";
$this->headTitle($this->title);
?>
 
<div class="hidden-phone span4">
	<?php echo $this->autsubmenu();?>
</div>
<div class="span8">
   <?php
     echo $this->partialLoop('partials/postlist_aut.phtml', $this->post);
     echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); 
   ?> 
</div>







