<?php if ($this->pageCount): ?>
<div class="pagination">
<!-- Ссылка на предыдущую страницу -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    &lt; Назад
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Назад</span> |
<?php endif; ?>
 
<!-- Нумерованные ссылки на страницы -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Ссылка на следующую страницу -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Вперед &gt;
  </a>
<?php else: ?>
  <span class="disabled">Вперед &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>