<div class="well">
	<h3><a href="<?php echo '/'.Zend_Registry::get('controller').'/selectpost/id/'.$this->id;?>"><?php echo $this->title; ?></a></h3>
	<h4></h4>
	<p><?php echo mb_substr($this->text, 0, 200);?> <a href="<?php echo '/'.Zend_Registry::get('controller').'/selectpost/id/'.$this->id;?>"> ... Подробнее</a>
		<br> 
	</p>
	<p><?php echo 'Оклад: ' . $this->price;?>
		<br> 
	</p>
	<p><?php echo Zend_Registry::get('seo_text').' ::       Просмотров: ' . ($this->review ? $this->review : 'нет');?>
		<br> 
	</p>
	<p><a href="<?php echo '/'.Zend_Registry::get('aut_controller').'/editpost/id/'.$this->id;?>">Редактировать</a>
		<br> 
	</p>	
</div>


