<?php 
	if ($this->partialCounter == 2 || $this->partialCounter == 5) {
		echo '<div class="breadcrumb">
				<!-- Яндекс.Директ -->
				<script type="text/javascript">
				//<![CDATA[
				yandex_partner_id = 114758;
				yandex_site_bg_color = \'EEEEEF\';
				yandex_site_charset = \'utf-8\';
				yandex_ad_format = \'direct\';
				yandex_font_size = 1;
				yandex_direct_type = \'horizontal\';
				yandex_direct_limit = 2;
				yandex_direct_title_font_size = 3;
				yandex_direct_title_color = \'0000CC\';
				yandex_direct_url_color = \'006600\';
				yandex_direct_text_color = \'000000\';
				yandex_direct_hover_color = \'0066FF\';
				yandex_direct_favicon = false;
				document.write(\'<sc\'+\'ript type=\"text/javascript\" src=\"http://an.yandex.ru/system/context.js\"></sc\'+\'ript>\');
				//]]>
				</script>
			</div>';
	} 
?>

<div class="well">
	<h3><a href="<?php echo '/'.Zend_Registry::get('controller').'/selectpost/id/'.$this->id;?>"><?php echo $this->title; ?></a></h3>
	<h4></h4>
	<p><?php echo mb_substr($this->text, 0, 200);?> <a href="<?php echo '/'.Zend_Registry::get('controller').'/selectpost/id/'.$this->id;?>"> ... Подробнее</a>
		<br> 
	</p>
	<p class="btn btn-warning"><?php echo 'Оклад: ' . $this->price;?>
		<br> 
	</p>
	<p><?php echo Zend_Registry::get('seo_text').' ::       Просмотров: ' . ($this->review ? $this->review : 'нет');?>
		<br> 
	</p>
</div>






