<?php
    $sitemap_options = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getApplication()->getOption('sitemap');
    $sitemap_url = $sitemap_options['url']; 
    $url = $sitemap_url.Zend_Registry::get('controller').'/selectpost/id/'.$this->id;
    
    $date = new Zend_Date(); 
    $createdDate= $date->get(Zend_Date::ISO_8601); 
    
    $text=str_replace("<br /> "," ",$this->text);
?>
<vacancy>
    <url><?php echo $url;?></url>
    <creation-date><?php echo $createdDate;?></creation-date>
    <category>
        <industry>Маркетинг, реклама, PR</industry>
    </category>
    <job-name><?php echo $this->title;?></job-name>
    <description><?php echo $text;?></description>
    <addresses>
        <address>
            <location><?php echo Zend_Registry::get('city_name');?></location>
        </address>
      </addresses>
    <anonymous-company>
        <description/>
    </anonymous-company>
</vacancy>