<?php
// Создаём заголовок страницы, который загрузится в layout
$this->title = $this->seo->GetByName('main_title')->text;
$this->headTitle($this->title);

$description = $this->seo->GetByName('main_description')->text;

$this->headMeta()->setName('description', $description);
$this->headMeta()->setName('keywords', 'вакансии, томск, требуется, агентства, работа');
?>

<div class="span8">
   <?php
     echo $this->partialLoop('partials/postlist.phtml', $this->post);
     echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); 
   ?> 
</div>
<div class="hidden-phone span4">
	<a href="<?php echo '/' . Zend_Registry::get('controller') . '/add' . $this->category_id ?>" class="btn btn-block btn-success">Добавить вакансию</a>
	<ul class="nav nav-tabs nav-stacked">
		<?php echo $this->partialLoop('partials/categorylist.phtml', $this->indexcategory);?>
	</ul>
</div>
